### PR TITLE
Update grid flex

### PR DESCRIPTION
**Pull request by dalecreativ**
Updated `coop-l-grid__item` to `display:flex` and `flex-direction:column`
Built to dist

### CODE REVIEW

**Comment by mchadwickweb** [comment]
What would the use case for this be? I might be wrong here, but this feels weird that we are assuming what sits in a grid item should be flexed and its children to be flex items. 

Could we not have some form of modifier to tackle the use case its trying to solve?

**Comment by froddd** [comment]
@mchadwickweb this is a good point too. Should the property of filling the parent container lie with the child rather than enforcing it with the grid item? The box model issue above would possibly point to letting the child decide if it should expand, as this changes its model quite drastically.

**Comment by dalecreativ** [comment]
> @mchadwickweb this is a good point too. Should the property of filling the parent container lie with the child rather than enforcing it with the grid item? The box model issue above would possibly point to letting the child decide if it should expand, as this changes its model quite drastically.

**Comment by colinrotherham** [comment]
@froddd This is the winning comment regarding margin collapsing.

It's pretty crucial for the type hierarchy to work correctly?

I'd make it opt-in via a utility class.

Or maybe you should nest another level of grid, or is that going too far?

**Comment by dalecreativ** [comment]
I'm going to close this.

**Pull request closed without merging**
